<a href="https://colab.research.google.com/github/Sirapatlnwza/Python_dataviz2023/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Exam

## Link DashBoard
https://lookerstudio.google.com/reporting/1635f258-3c79-44a2-b10a-331c03d5657d

## สมาชิกในกลุ่ม
1. นายเศรษฐา สุวินชัย 633020361-5 หน้าที่ Dashboard
2. นางสาวพิมพิกา ยอดศรี 643020511-3 หน้าที่ Dashboard
3. นายภัทรธร ก้อนมณี 643020513-9 หน้าที่ Coding
4. นายรัชชานนท์ ทิพย์พิมานพร 643020515-5 หน้าที่ Coding
5. นางสาวรัตชฎากร นามวงศ์ 643020517-1 หน้าที่ Dashboard
6. นางสาวสิรภัทร ไชยมาตย์ 643020523-6 หน้าที่ Dashboard

## Import data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# เข้า path ที่เราสนใจใน google drive
import os
os.chdir('/content/drive/MyDrive/DataViz_FinalData')

In [ ]:
!ls # เช็คว่ามีไฟล์อะไรบ้างที่อยู่ใน path นั้น

2017.csv       Operation.gsheet				POS_transactions_20190213-20190226.csv
201902.csv     POS_operator_logs_20171207-20171219.csv	POS_transactions_20190328-20190410.csv
201904.csv     POS_operator_logs_20190213-20190226.csv	tran.csv
Data.csv       POS_operator_logs_20190328-20190410.csv	tran.gsheet
Operation.csv  POS_transactions_20171207-20171219.csv	x.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_op1 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_operator_logs_20171207-20171219.csv')
df_op2 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_operator_logs_20190213-20190226.csv')
df_op3 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_operator_logs_20190328-20190410.csv')
df_tran1 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_transactions_20171207-20171219.csv')
df_tran2 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_transactions_20190213-20190226.csv')
df_tran3 = pd.read_csv('/content/drive/MyDrive/DataViz_FinalData/POS_transactions_20190328-20190410.csv')

In [ ]:
df_op1

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
4703,8,14,171219106014514,2017-12-19T22:00:22,264,OperatorSignOff
4704,1,21,171219106021873,2017-12-19T22:02:53,124,OperatorSignOn
4705,8,15,171219106015506,2017-12-19T22:05:05,265,OperatorSignOff
4706,1,21,171219106021890,2017-12-19T22:09:47,124,OperatorSignOff
4707,1,22,171219106022935,2017-12-19T22:12:44,146,OperatorSignOff

In [ ]:
df_op2

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1902131060192,2019-02-13T05:37:55,269,OperatorSignOn
1,8,18,1902131060182,2019-02-13T05:37:55,268,OperatorSignOn
2,8,17,1902131060172,2019-02-13T05:38:43,267,OperatorSignOn
3,1,4,190213106042,2019-02-13T07:01:26,332,OperatorSignOn
4,1,7,190213106072,2019-02-13T07:01:57,10,OperatorSignOn
...,...,...,...,...,...,...
5213,1,12,190226106012628,2019-02-26T21:44:52,332,OperatorUnLock
5214,1,20,190226106020667,2019-02-26T21:53:12,131,OperatorSignOff
5215,1,12,190226106012644,2019-02-26T22:00:49,332,OperatorLock
5216,1,12,190226106012645,2019-02-26T22:01:48,332,OperatorUnLock
5217,1,12,190226106012648,2019-02-26T22:03:46,332,OperatorSignOff

In [ ]:
df_op3

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1903281060192,2019-03-28T06:08:13,269,OperatorSignOn
1,8,18,1903281060182,2019-03-28T06:09:13,268,OperatorSignOn
2,8,17,1903281060172,2019-03-28T06:08:33,267,OperatorSignOn
3,1,4,190328106042,2019-03-28T07:04:45,104,OperatorSignOn
4,1,6,190328106062,2019-03-28T07:18:38,125,OperatorSignOn
...,...,...,...,...,...,...
4173,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
4174,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
4175,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
4176,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
4177,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [ ]:
op_concat = pd.concat([df_op1,df_op2,df_op3], ignore_index = True)
op_concat

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
14099,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
14100,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
14101,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
14102,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
14103,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [ ]:
op = op_concat[['OperatorID','BeginDateTime','Items']]

In [ ]:
op

       OperatorID       BeginDateTime            Items
0             266 2017-12-07 06:04:01   OperatorSignOn
1             265 2017-12-07 06:04:15   OperatorSignOn
2             264 2017-12-07 06:05:36   OperatorSignOn
3             268 2017-12-07 06:05:41   OperatorSignOn
4             267 2017-12-07 06:05:56   OperatorSignOn
...           ...                 ...              ...
14099         104 2019-04-10 21:53:58  OperatorSignOff
14100         304 2019-04-10 21:54:30  OperatorSignOff
14101         104 2019-04-10 21:55:05   OperatorSignOn
14102         136 2019-04-10 22:00:25  OperatorSignOff
14103         104 2019-04-10 22:10:57  OperatorSignOff

[14104 rows x 3 columns]

In [ ]:
df_tran1

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
66858,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27
66859,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16
66860,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58
66861,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96
66862,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58

In [ ]:
df_tran2

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.790000
1,1,190213106054,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.190000
2,1,190213106055,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.200000
3,1,190213106058,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.200000
4,1,190213106059,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.200000
...,...,...,...,...,...,...,...,...,...,...,...
47061,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.450000
47062,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.970000
47063,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.340000
47064,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.420000
47065,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.380000

In [ ]:
df_tran3

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000
1,1,19032910607385.000000,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.740000
2,1,19032910607386.000000,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.470000
3,1,19032910607387.000000,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.180000
4,1,19032910607389.000000,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.700000
...,...,...,...,...,...,...,...,...,...,...,...
49335,1,190410100000000.000000,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.140000
49336,1,190410100000000.000000,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.900000
49337,1,190410100000000.000000,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.990000
49338,1,190410100000000.000000,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.880000
49339,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000

In [ ]:
tran_concat = pd.concat([df_tran1,df_tran2,df_tran3], ignore_index = True)
tran_concat

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
163264,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14
163265,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90
163266,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99
163267,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88
163268,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33

In [ ]:
# กำหนดตัวเลือกแสดงผลตัวเลข
pd.set_option('display.float_format', '{:.6f}'.format)

In [ ]:
# ตัดทศนิยม ใน TranID
columns_to_format = ['TranID']

def remove_decimal(value):
    return int(value)

tran_concat[columns_to_format] = tran_concat[columns_to_format].apply(lambda x: x.apply(remove_decimal))

In [ ]:
tran_concat

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.710000
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.760000
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.770000
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.880000
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.340000
...,...,...,...,...,...,...,...,...,...,...,...
163264,1,190410100000000,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.140000
163265,1,190410100000000,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.900000
163266,1,190410100000000,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.990000
163267,1,190410100000000,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.880000
163268,1,190410100000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000

## Checking Missing Values

In [ ]:
op_concat.isnull().any() # ตาราง operator 'ข้อมูลการสั่งซื้อ' ไม่มีค่า Null

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [ ]:
tran_concat.isnull().any() # ตาราง transection 'ข้อมูลการสั่งซื้อ' ไม่มีค่า Null

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [ ]:
tran = tran_concat[['TranID','BeginDateTime','EndDateTime','OperatorID','TranTime']]

In [ ]:
x = op.merge(tran, on='OperatorID',how = 'inner')

In [ ]:
x

,OperatorID,BeginDateTime_x,Items,TranID,BeginDateTime_y,EndDateTime,TranTime
0,266,2017-12-07T06:04:01,OperatorSignOn,1712071060164,2017-12-07T07:09:47,2017-12-07T07:10:28,41
1,266,2017-12-07T06:04:01,OperatorSignOn,1712071060167,2017-12-07T07:14:57,2017-12-07T07:16:09,72
2,266,2017-12-07T06:04:01,OperatorSignOn,1712071060169,2017-12-07T07:17:21,2017-12-07T07:20:33,192
3,266,2017-12-07T06:04:01,OperatorSignOn,17120710601611,2017-12-07T07:22:03,2017-12-07T07:24:03,120
4,266,2017-12-07T06:04:01,OperatorSignOn,17120710601613,2017-12-07T07:25:21,2017-12-07T07:25:34,13
...,...,...,...,...,...,...,...
46476693,304,2019-04-10T21:54:30,OperatorSignOff,190410100000000,2019-04-10T21:48:03,2019-04-10T21:48:17,14
46476694,304,2019-04-10T21:54:30,OperatorSignOff,190410100000000,2019-04-10T21:48:34,2019-04-10T21:49:19,45
46476695,304,2019-04-10T21:54:30,OperatorSignOff,190410100000000,2019-04-10T21:49:31,2019-04-10T21:50:07,36
46476696,304,2019-04-10T21:54:30,OperatorSignOff,190410100000000,2019-04-10T21:50:29,2019-04-10T21:51:32,63
46476697,304,2019-04-10T21:54:30,OperatorSignOff,190410100000000,2019-04-10T21:52:04,2019-04-10T21:52:49,45

In [ ]:
x.isnull().any()

KeyboardInterrupt: ignored

In [ ]:
print(x.shape)
x.dropna()

In [ ]:
x.duplicated()

In [ ]:
x.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','Data.csv'))

In [ ]:
tran_concat.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','tran.csv'))

In [ ]:
op_concat.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','Operation.csv'))

## Test

In [ ]:
bool_series = op_concat.duplicated(subset='TranID')
# passing NOT of bool series to see unique values only
x4 = op_concat[~bool_series]
# displaying data
x5 = x4.reset_index()

In [ ]:
bool_series = tran_concat.duplicated(subset='TranID')
# passing NOT of bool series to see unique values only
x6 = tran_concat[~bool_series]
# displaying data
x7 = x6.reset_index()

In [ ]:
op1 = x5[['WorkstationGroupID','WorkstationID','TranID','OperatorID','Items']]

In [ ]:
op1

,WorkstationGroupID,WorkstationID,TranID,OperatorID,Items
0,8,16,1712071060162,266,OperatorSignOn
1,8,15,1712071060152,265,OperatorSignOn
2,8,14,1712071060142,264,OperatorSignOn
3,8,18,1712071060182,268,OperatorSignOn
4,8,17,1712071060172,267,OperatorSignOn
...,...,...,...,...,...
14069,1,3,19041010603798,104,OperatorSignOff
14070,1,4,190410106041042,304,OperatorSignOff
14071,1,4,190410106041044,104,OperatorSignOn
14072,1,5,19041010605515,136,OperatorSignOff
14073,1,4,190410106041061,104,OperatorSignOff

In [ ]:
tran1 = x7[['WorkstationGroupID','TranID','OperatorID','ArtNum','TNcash','TNcard','Amount']]

In [ ]:
tran1 = tran1.applymap(int)

In [ ]:
tran1

,WorkstationGroupID,TranID,OperatorID,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,101,23,1,0,112
1,1,171207106022465,101,29,1,0,54
2,1,171207106022466,101,3,1,0,14
3,1,171207106022467,101,12,1,0,37
4,1,171207106022468,101,7,1,0,115
...,...,...,...,...,...,...,...
126954,1,190402106084,603,8,1,0,24
126955,1,190402106085,603,17,1,0,51
126956,1,190402106086,603,19,1,0,41
126957,1,190402106087,603,9,0,1,47
126958,1,190402106089,603,6,1,0,17

In [ ]:
x1 = op1.merge(tran1, on='OperatorID',how = 'inner')

In [ ]:
x1

,WorkstationGroupID_x,WorkstationID,TranID_x,OperatorID,Items,WorkstationGroupID_y,TranID_y,ArtNum,TNcash,TNcard,Amount
0,8,16,1712071060162,266,OperatorSignOn,8,1712071060164,4,0,1,11
1,8,16,1712071060162,266,OperatorSignOn,8,1712071060167,5,0,1,16
2,8,16,1712071060162,266,OperatorSignOn,8,1712071060169,12,0,1,29
3,8,16,1712071060162,266,OperatorSignOn,8,17120710601611,12,0,1,62
4,8,16,1712071060162,266,OperatorSignOn,8,17120710601613,1,0,1,27
...,...,...,...,...,...,...,...,...,...,...,...
36925352,1,4,19041010604968,304,OperatorLock,1,190410106089,2,1,0,13
36925353,1,4,19041010604969,304,OperatorUnLock,1,190410106088,2,1,0,7
36925354,1,4,19041010604969,304,OperatorUnLock,1,190410106089,2,1,0,13
36925355,1,4,190410106041042,304,OperatorSignOff,1,190410106088,2,1,0,7
36925356,1,4,190410106041042,304,OperatorSignOff,1,190410106089,2,1,0,13

In [ ]:
x1.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','Data.csv'))

## แบ่งตามช่วงเวลา

In [ ]:
df2017=df_tran1.merge(df_op1[['OperatorID','BeginDateTime','Items']],how= 'left',on='OperatorID')

In [ ]:
df201902=df_tran2.merge(df_op2[['OperatorID','BeginDateTime','Items']],how= 'left',on='OperatorID')

In [ ]:
df201904=df_tran3.merge(df_op3[['OperatorID','BeginDateTime','Items']],how= 'left',on='OperatorID')

In [ ]:
df2017.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','2017.csv'))
df201902.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','201902.csv'))
df201904.to_csv(os.path.join('/content/drive/MyDrive/DataViz_FinalData','201904.csv'))

## สิ่งที่สนใจ

### 1. ลูกค้าส่วนใหญ่นิยมจ่ายด้วย cash หรือ card มากกว่ากัน (TNcash,TNcard ข้อมูลซื้อ)

In [ ]:
tran_concat[(tran_concat['TNcard']== False) & (tran_concat['TNcash']== False)]

In [ ]:
tran_concat_drop = tran_concat[~((tran_concat['TNcard'] == False) & (tran_concat['TNcash'] == False))]
tran_concat_drop

In [ ]:
tran_concat_drop['TNcash'] = tran_concat['TNcash'].replace('True', 'Cash')

In [ ]:
tran_concat_drop

In [ ]:
tran_concat_drop['TNcash']

### 2. ลูกค้าส่วนใหญ่นิยมใช้บริการแบบ service หรือ self-service (WorkStationGroupID ข้อมูลซื้อ)

In [ ]:
Service = tran_concat[tran_concat['WorkstationGroupID']==1]
Service

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.710000
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.760000
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.770000
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.880000
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.340000
...,...,...,...,...,...,...,...,...,...,...,...
163264,1,190410100000000,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.140000
163265,1,190410100000000,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.900000
163266,1,190410100000000,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.990000
163267,1,190410100000000,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.880000
163268,1,190410100000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000

In [ ]:
Service.describe()

,WorkstationGroupID,TranID,OperatorID,TranTime,BreakTime,ArtNum,Amount
count,123207.000000,123207.000000,123207.000000,123207.000000,123207.000000,123207.000000,123207.000000
mean,1.000000,82062883645216.593750,171.380368,62.037441,25.732239,17.657706,82.355843
std,0.000000,87465824110894.359375,109.956414,48.369568,52.336845,17.649914,93.506244
min,1.000000,171207106044.000000,10.000000,0.000000,-12.000000,1.000000,0.000000
25%,1.000000,19021510605544.500000,112.000000,28.000000,12.000000,6.000000,25.740000
50%,1.000000,19040410000000.000000,125.000000,50.000000,17.000000,12.000000,53.790000
75%,1.000000,171214106021325.500000,143.000000,82.000000,25.000000,23.000000,106.580000
max,1.000000,1712121060201027.000000,606.000000,697.000000,1199.000000,500.000000,6883.500000

In [ ]:
SelfService = tran_concat[tran_concat['WorkstationGroupID']==8]
SelfService

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
45410,8,1712071060144,2017-12-07T07:00:41,2017-12-07T07:01:33,264,52,388,2,False,True,23.980000
45411,8,1712071060146,2017-12-07T07:08:01,2017-12-07T07:09:58,264,117,93,9,False,True,73.600000
45412,8,1712071060148,2017-12-07T07:11:31,2017-12-07T07:15:09,264,218,44,7,False,True,21.450000
45413,8,17120710601410,2017-12-07T07:15:53,2017-12-07T07:17:00,264,67,84,7,False,True,64.820000
45414,8,17120710601412,2017-12-07T07:18:24,2017-12-07T07:18:40,264,16,95,1,False,True,1.090000
...,...,...,...,...,...,...,...,...,...,...,...
155991,8,190410100000000,2019-04-10T21:02:02,2019-04-10T21:04:06,269,124,45,9,True,False,91.370000
155992,8,190410100000000,2019-04-10T21:04:51,2019-04-10T21:05:10,269,19,23,1,True,False,3.490000
155993,8,190410100000000,2019-04-10T21:05:33,2019-04-10T21:05:56,269,23,38,1,False,True,10.990000
155994,8,190410100000000,2019-04-10T21:06:34,2019-04-10T21:07:35,269,61,56,4,False,True,33.960000
155995,8,190410100000000,2019-04-10T21:08:31,2019-04-10T21:09:24,269,53,99,5,False,True,36.940000

In [ ]:
SelfService.describe()

,WorkstationGroupID,TranID,OperatorID,TranTime,BreakTime,ArtNum,Amount
count,40062.000000,40062.000000,40062.000000,40062.000000,40062.000000,40062.000000,40062.000000
mean,8.000000,141961632593108.031250,267.251286,99.512331,92.572987,8.980580,42.724743
std,0.000000,70608977363693.906250,1.511208,82.027384,98.313290,9.005207,53.062391
min,8.000000,1712071060144.000000,264.000000,0.000000,5.000000,1.000000,-3.440000
25%,8.000000,171207106015402.500000,267.000000,42.000000,38.000000,3.000000,11.990000
50%,8.000000,171216106017256.000000,268.000000,77.000000,62.000000,6.000000,27.295000
75%,8.000000,190223106019309.750000,268.000000,131.000000,107.000000,12.000000,55.515000
max,8.000000,190410100000000.000000,269.000000,1137.000000,1199.000000,103.000000,4199.160000

### 3. จำนวนครั้งของสถานะแคชเชียร์แต่ละประเภท (Items ข้อมูลlogin)

In [ ]:
OperatorSignON = op_concat[op_concat['Items']=='OperatorSignOn']
OperatorSignONGroup = op_concat[op_concat['Items']=='OperatorSignOn'].groupby('Items').count().reset_index()
OperatorSignONGroup

,Items,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID
0,OperatorSignOn,3494,3494,3494,3494,3494

In [ ]:
OperatorSignOff = op_concat[op_concat['Items']=='OperatorSignOff']
OperatorSignOffGroup = op_concat[op_concat['Items']=='OperatorSignOff'].groupby('Items').count().reset_index()
OperatorSignOffGroup

,Items,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID
0,OperatorSignOff,3485,3485,3485,3485,3485

In [ ]:
OperatorUnlock = op_concat[op_concat['Items']=='OperatorUnLock']
OperatorUnLockGroup = op_concat[op_concat['Items']=='OperatorUnLock'].groupby('Items').count().reset_index()
OperatorUnLockGroup

,Items,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID
0,OperatorUnLock,3559,3559,3559,3559,3559

In [ ]:
Operatorlock = op_concat[op_concat['Items']=='OperatorLock']
OperatorLockGroup = op_concat[op_concat['Items']=='OperatorLock'].groupby('Items').count().reset_index()
OperatorLockGroup

,Items,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID
0,OperatorLock,3566,3566,3566,3566,3566

### 4. เปรียบเทียบการทำงานระหว่างเช้า (06:00:00-11:59:59)และ บ่าย (12:00:00-23:59:59) เป็นจำนวนครั้ง  (ข้อมูลlogin) (คำนวณจำนวนครั้ง,items >>รวมกับข้อ3เลยก้ได้)

### 5. ระยะเวลาโดยเฉลี่ยที่ลูกค้าทำ transaction ต่อคน  (TranTimeข้อมูลการซื้อ)

In [ ]:
tran_concat

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.710000
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.760000
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.770000
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.880000
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.340000
...,...,...,...,...,...,...,...,...,...,...,...
163264,1,190410100000000,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.140000
163265,1,190410100000000,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.900000
163266,1,190410100000000,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.990000
163267,1,190410100000000,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.880000
163268,1,190410100000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000

In [ ]:
avg_trantime = tran_concat['TranTime'].mean()
avg_trantime

71.23281210762606

### 6. รายได้รวมแต่ละวัน (Amount ข้อมูลการซื้อ)

In [ ]:
df2017

,WorkstationGroupID,TranID,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,BeginDateTime_y,Items
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,2017-12-07T14:23:11,OperatorSignOn
1,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,2017-12-07T15:04:20,OperatorLock
2,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,2017-12-07T15:04:57,OperatorUnLock
3,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,2017-12-07T15:05:47,OperatorLock
4,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,2017-12-07T15:06:58,OperatorUnLock
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328677,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,2017-12-19T11:32:55,OperatorLock
7328678,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,2017-12-19T11:33:16,OperatorUnLock
7328679,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,2017-12-19T11:41:57,OperatorLock
7328680,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,2017-12-19T11:48:24,OperatorUnLock
7328681,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,2017-12-19T11:55:11,OperatorSignOff

In [ ]:
Amount_sum2017 = df2017[['Amount']].sum()
Amount_sum2017

Amount   611817482.780001
dtype: float64

In [ ]:
df201902

,WorkstationGroupID,TranID,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,BeginDateTime_y,Items
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2019-02-13T07:01:57,OperatorSignOn
1,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2019-02-13T07:02:16,OperatorSignOff
2,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2019-02-13T10:32:12,OperatorSignOn
3,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2019-02-13T10:32:15,OperatorSignOff
4,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2019-02-13T10:32:43,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8638567,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2019-02-23T17:32:11,OperatorSignOff
8638568,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2019-02-23T18:35:29,OperatorSignOn
8638569,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2019-02-23T19:29:15,OperatorSignOff
8638570,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2019-02-23T19:36:38,OperatorSignOn
8638571,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2019-02-23T19:46:27,OperatorSignOff

In [ ]:
Amount_sum201902 = df201902[['Amount']].sum()
Amount_sum201902

Amount   636539914.799999
dtype: float64

In [ ]:
df201904

,WorkstationGroupID,TranID,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,BeginDateTime_y,Items
0,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000,2019-03-28T08:05:15,OperatorSignOn
1,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000,2019-03-28T08:05:15,OperatorSignOff
2,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000,2019-03-28T10:37:43,OperatorSignOn
3,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000,2019-03-28T10:38:16,OperatorSignOff
4,1,19040310601356.000000,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.990000,2019-03-28T11:02:21,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5905669,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000,2019-04-10T12:03:11,OperatorSignOff
5905670,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000,2019-04-10T13:39:49,OperatorSignOn
5905671,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000,2019-04-10T13:51:42,OperatorLock
5905672,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000,2019-04-10T13:52:27,OperatorUnLock
5905673,1,190410100000000.000000,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.330000,2019-04-10T14:12:35,OperatorSignOff

In [ ]:
Amount_sum201904 = df201904[['Amount']].sum()
Amount_sum201904

Amount   457772197.600000
dtype: float64